name: k8zdev
description: "k8s admin app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+13

environment:
  sdk: ">=3.2.6 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # ------- custom packages --------
  go_router: ^13.1.0
  google_nav_bar: ^5.0.6
  settings_ui: ^2.0.2
  intl: ^0.18.1
  provider: ^6.1.1
  window_manager: ^0.3.8
  talker_flutter: ^4.0.0
  sqflite: ^2.3.2
  stash: ^5.1.0
  stash_sqlite: ^5.2.0
  package_info_plus: ^5.0.1
  sqlite_viewer: ^1.0.5
  connectivity_plus: ^5.0.2
  path: ^1.8.3
  kubeconfig: ^1.0.2
  code_editor:
    git:
      url: https://github.com/kofj/code_editor
      ref: dev/show_toolbar_option
  file_selector: ^1.0.2
  path_provider: ^2.1.2
  flutter_multi_select_items: ^0.4.2
  material_dialogs: ^1.1.4
  ffi: ^2.0.1
  collection: ^1.18.0
  icons_plus: ^5.0.0
  geekyants_flutter_gauges: ^1.0.3
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.15
  firebase_analytics: ^10.8.6
  archive: ^3.4.10
  purchases_flutter: ^6.21.1
  url_launcher: ^6.2.5
  flutter_slidable: ^3.0.1
  xterm: ^3.5.0
  web_socket_channel: ^2.4.2
  chinese_font_library: ^1.1.0
  http: ^1.2.0

dependency_overrides:
  meta: 1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  icons_launcher: ^2.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icon/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DroidSansMNerdFontMono
      fonts:
        - asset: assets/fonts/DroidSansMNerdFontMono-Regular.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

icons_launcher:
  image_path: "assets/icon@8x.png"
  platforms:
    ios:
      enable: true
      image_path: "assets/Icon2x.png"
    macos:
      enable: true
